# Generated by Django 4.0.1 on 2022-02-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
